before_script:
  - mkdir ~/.siriproxy
  - cp ci/config.yml ~/.siriproxy
branches:
  only:
    - rspec
rvm:
  - 1.9.3
notifications:
  irc: "irc.freenode.org#siriproxy"
  recipients:
    - wael.nasreddine@gmail.com
